steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        '--cache-from',
        'europe-west1-docker.pkg.dev/tao-artefacts/devkit/lti-devkit:develop',
        "-t",
        "europe-west1-docker.pkg.dev/tao-artefacts/devkit/lti-devkit:$COMMIT_SHA",
        "-t",
        "europe-west1-docker.pkg.dev/tao-artefacts/devkit/lti-devkit:${_BRANCH_NAME}",
        -f,
        "./docker/kube/Dockerfile",
        ".",
      ]
images:
  - "europe-west1-docker.pkg.dev/tao-artefacts/devkit/lti-devkit:$COMMIT_SHA"
  - 'europe-west1-docker.pkg.dev/tao-artefacts/devkit/lti-devkit:${_BRANCH_NAME}'

substitutions:
  _BRANCH_NAME: ${BRANCH_NAME//\//-}
options:
  machineType: E2_HIGHCPU_32
  dynamic_substitutions: true