home:
    path: /
    controller: App\Action\HomeAction

platform_message_launch_lti_resource_link:
    path: /platform/message/launch/lti-resource-link
    controller: App\Action\Platform\Message\LtiResourceLinkLaunchAction

platform_message_launch_deep_linking:
    path: /platform/message/launch/deep-linking
    controller: App\Action\Platform\Message\DeepLinkingLaunchAction

platform_message_deep_linking_return:
    path: /platform/message/return/deep-linking
    controller: App\Action\Platform\Message\DeepLinkingReturnAction

platform_message_launch_proctoring:
    path: /platform/message/launch/proctoring
    controller: App\Action\Platform\Message\ProctoringLaunchAction

platform_message_proctoring_return:
    path: /platform/message/return/proctoring
    controller: App\Action\Platform\Message\ProctoringReturnAction

tool_message_launch:
    path: /tool/launch
    controller: App\Action\Tool\Message\MessageLaunchAction

tool_message_deep_linking_response:
    methods: [POST]
    path: /tool/deep-linking-response
    controller: App\Action\Tool\Message\DeepLinkingResponseAction

tool_message_proctoring_response:
    methods: [POST]
    path: /tool/proctoring-response
    controller: App\Action\Tool\Message\ProctoringResponseAction

tool_service_client:
    path: /tool/service/client
    controller: App\Action\Tool\Service\LtiServiceClientAction

platform_ajax_default_registration_url:
    path: /platform/ajax/registration-url
    controller: App\Action\Platform\Ajax\RegistrationDefaultLaunchUrlAction
    condition: "request.isXmlHttpRequest()"

tool_ajax_service_client_autocomplete:
    path: /tool/ajax/service-client/autocomplete
    controller: App\Action\Tool\Ajax\LtiServiceClientAutocompleteAction
    condition: "request.isXmlHttpRequest()"

tool_ajax_service_nrps:
    path: /tool/ajax/nrps
    controller: App\Action\Tool\Ajax\NrpsServiceClientAction
    condition: "request.isXmlHttpRequest()"

tool_ajax_service_basic_outcome:
    path: /tool/ajax/basic-outcome
    controller: App\Action\Tool\Ajax\BasicOutcomeServiceClientAction
    condition: "request.isXmlHttpRequest()"

tool_ajax_service_acs:
    path: /tool/ajax/acs
    controller: App\Action\Tool\Ajax\AcsServiceClientAction
    condition: "request.isXmlHttpRequest()"

platform_service_nrps:
    methods: [GET]
    path: /platform/service/nrps/{contextIdentifier}/memberships/{membershipIdentifier}
    controller: app.service.nrps_membership_controller

platform_service_acs:
    methods: [POST]
    path: /platform/service/acs/{assessmentIdentifier}
    controller: app.service.proctoring_acs_controller

platform_basic_outcome_results:
    methods: [POST]
    path: /platform/service/basic-outcome
    controller: app.service.basic_outcome_controller

platform_ags_list_scores:
    methods: [GET]
    path: /platform/service/ags-list-scores
    controller: App\Action\Platform\Service\Ags\HomeAction

platform_ags_delete_scores:
    methods: [GET]
    path: /platform/service/ags-delete-scores
    controller: App\Action\Platform\Service\Ags\DeleteScoresAction

platform_ags_create_score:
    methods: [POST]
    path: /platform/service/ags/{contextId}/lineitems/{lineItemId}/scores
    controller: App\Action\Platform\Service\Ags\CreateScoreAction

platform_basic_outcome_list:
    methods: [GET]
    path: /platform/basic-outcomes
    controller: App\Action\Platform\BasicOutcome\ListBasicOutcomesAction

platform_basic_outcome_delete:
    methods: [GET]
    path: /platform/basic-outcomes/{basicOutcomeIdentifier}/delete
    controller: App\Action\Platform\BasicOutcome\DeleteBasicOutcomeAction

platform_nrps_list_memberships:
    methods: [GET]
    path: /platform/nrps/memberships
    controller: App\Action\Platform\Nrps\ListMembershipsAction

platform_nrps_create_membership:
    methods: [GET, POST]
    path: /platform/nrps/memberships/new
    controller: App\Action\Platform\Nrps\CreateMembershipAction

platform_nrps_view_membership:
    methods: [GET]
    path: /platform/nrps/memberships/{membershipIdentifier}/view
    controller: App\Action\Platform\Nrps\ViewMembershipAction

platform_nrps_edit_membership:
    methods: [GET, POST]
    path: /platform/nrps/memberships/{membershipIdentifier}/edit
    controller: App\Action\Platform\Nrps\EditMembershipAction

platform_nrps_delete_membership:
    methods: [GET]
    path: /platform/nrps/memberships/{membershipIdentifier}/delete
    controller: App\Action\Platform\Nrps\DeleteMembershipAction

platform_proctoring_list_assessments:
    methods: [GET]
    path: /platform/prtoctoring/assessments
    controller: App\Action\Platform\Proctoring\ListAssessmentsAction

platform_proctoring_create_assessment:
    methods: [GET, POST]
    path: /platform/proctoring/assessments/new
    controller: App\Action\Platform\Proctoring\CreateAssessmentAction

platform_proctoring_view_assessment:
    methods: [GET]
    path: /platform/proctoring/assessments/{assessmentIdentifier}/view
    controller: App\Action\Platform\Proctoring\ViewAssessmentAction

platform_proctoring_edit_assessment:
    methods: [GET, POST]
    path: /platform/proctoring/assessments/{assessmentIdentifier}/edit
    controller: App\Action\Platform\Proctoring\EditAssessmentAction

platform_proctoring_delete_assessment:
    methods: [GET]
    path: /platform/proctoring/assessments/{assessmentIdentifier}/delete
    controller: App\Action\Platform\Proctoring\DeleteAssessmentAction
