parameters:
    editor_claims:
        AGS:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_AGS
            value:
                scope: [
                        'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem',
                        'https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly',
                        'https://purl.imsglobal.org/spec/lti-ags/scope/score'
                ]
                lineitems: '%application_host%/platform/service/ags/default/lineitems'
                lineitem: '%application_host%/platform/service/ags/default/lineitems/label'
        ACS:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_ACS
            value:
                actions: [
                    'pause',
                    'resume',
                    'terminate',
                    'update',
                    'flag'
                ]
                assessment_control_url: '{url|required}'
        Basic Outcome:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_BASIC_OUTCOME
            value:
                lis_result_sourcedid: 'default'
                lis_outcome_service_url: '%application_host%/platform/service/basic-outcome'
        Context:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_CONTEXT
            value:
                id: 'default'
                type: []
                label: '{string|optional}'
                title: '{string|optional}'
        Launch presentation:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_LAUNCH_PRESENTATION
            value:
                document_target: '{string|optional}'
                height: '{int|optional}'
                width: '{int|optional}'
                return_url: '{url|optional}'
                locale: '{string|optional}'
        LIS:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_LIS
            value:
                course_offering_sourcedid: '{string|optional}'
                course_section_sourcedid: '{string|optional}'
                outcome_service_url: '{url|optional}'
                person_sourcedid: '{string|optional}'
                result_sourcedid: '{string|optional}'
        NRPS:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_NRPS
            value:
                context_memberships_url: '%application_host%/platform/service/nrps/default/memberships/default'
                service_versions: ['2.0']
        Platform instance:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_TOOL_PLATFORM
            value:
                guid: '{string|required}'
                contact_email: '{string|optional}'
                description: '{string|optional}'
                name: '{string|optional}'
                url: '{url|optional}'
                product_family_code: '{string|optional}'
                version: '{string|optional}'
        Resource link:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_RESOURCE_LINK
            value:
                id: '{string|required}'
                title: '{string|optional}'
                description: '{string|optional}'
        Roles:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_ROLES
            value: ['http://purl.imsglobal.org/vocab/lis/v2/membership#Learner']
        Custom – Review:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_CUSTOM
            value:
                deliverySettings.review.enabled: 'true'
                deliverySettings.review.showCorrect: 'true'
                deliverySettings.review.showScore: 'true'
                deliverySettings.review.showQuestion: 'false'
                deliverySettings.review.showUnShuffled: 'true'
                deliverySettings.review.allInOne: 'false'
        Custom – Proctored:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_CUSTOM
            value:
                proctoringSettings.enableMonitoring: 'true'
                proctoringSettings.requireProctorAuthorization: 'true'
        Custom – Plugins:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_CUSTOM
            value:
                deliverySettings.plugins.add: 'taoQtiNuiTest/runner/plugins/panel/a11y/plugin'
                deliverySettings.plugins.remove: 'taoQtiNuiTest/runner/plugins/tools/highlighter/plugin,taoQtiNuiTest/runner/plugins/tools/scratchpad/plugin'
                deliverySettings.plugins: '{"readAloud": {"readAloudOption": "always-enabled"}, "a11yMenuPanel": {"openOnStart": true, "contrastTheme": {"enabled": true, "themes": ["default", "whiteOnBlue", "yellowOnBlack", "blueOnYellow", "greyOnGreen"]}, "groups": ["group-contrast", "group-pointer", "group-text", "group-zoom"]}}'
        Custom – Item Runner:
            name: !php/const \OAT\Library\Lti1p3Core\Message\Payload\LtiMessagePayloadInterface::CLAIM_LTI_CUSTOM
            value:
                deliverySettings.itemRunnerConfigElements: '{"ExtendedTextInteraction": {"spellCheckConfig": {"enabled": true, "providerId": "wproofreader", "providerConfig": {"lang": "nb_NO"}}}}'